fix Invalid script name
Object tool ID generated: 10040
InputField [name=size, type=NUMBER, displayName=Size (bytes), orderNumber=0, flags=0]
InputField [name=unused, type=PASSWORD, displayName=Unused field, orderNumber=0, flags=0]
[Network Message Receiver] INFO org.netxms.client.NXCSession - Network receiver thread stopped
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.258 s <<< FAILURE! -- in org.netxms.tests.ObjectToolsTest
[ERROR] org.netxms.tests.ObjectToolsTest.testInputGlobalVar -- Time elapsed: 1.017 s <<< ERROR!
org.netxms.client.NXCException: Invalid script name
        at org.netxms.client.NXCSession.waitForRCC(NXCSession.java:2084)
        at org.netxms.client.NXCSession.waitForRCC(NXCSession.java:2049)
        at org.netxms.client.NXCSession.processScriptExecution(NXCSession.java:8477)
        at org.netxms.client.NXCSession.executeLibraryScript(NXCSession.java:8547)
        at org.netxms.client.NXCSession.executeLibraryScript(NXCSession.java:8510)
        at org.netxms.tests.ObjectToolsTest.testInputGlobalVar(ObjectToolsTest.java:194)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)