WIP, BAD
mvn -f tests/integration/pom.xml test -P integration-test -fae --debug -Dtest=ObjectToolsTest
...
[main] INFO org.netxms.client.NXCSession - Succesfully logged in, userId=1
Object tool ID generated: 10022
InputField [name=size, type=NUMBER, displayName=Size (bytes), orderNumber=0, flags=0]
InputField [name=unused, type=PASSWORD, displayName=Unused field, orderNumber=0, flags=0]
[Network Message Receiver] INFO org.netxms.client.NXCSession - Network receiver thread stopped
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.347 s <<< FAILURE! -- in org.netxms.tests.ObjectToolsTest
[ERROR] org.netxms.tests.ObjectToolsTest.testInputGlobalVar -- Time elapsed: 1.017 s <<< ERROR!
org.netxms.client.NXCException: Invalid object ID
        at org.netxms.client.NXCSession.waitForRCC(NXCSession.java:2084)
        at org.netxms.client.NXCSession.waitForRCC(NXCSession.java:2049)
        at org.netxms.client.NXCSession.executeServerCommand(NXCSession.java:10042)
        at org.netxms.tests.ObjectToolsTest.testInputGlobalVar(ObjectToolsTest.java:144)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

excerpt of netxmsd.log:

2024.07.11 18:04:10.467 *D* [client.session.0   ] Message dump:
  ** 000000 | 00 1D 50 00 00 00 00 20 00 00 00 09 00 00 00 01 | ..P.... ........
  ** 000010 | 00 00 00 1C 00 00 00 00 00 00 00 00 00 00 00 00 | ................
  ** code=0x001D (CMD_REQUEST_COMPLETED) version=5 flags=0x0000 id=9 size=32 numFields=1
  ** 000000: [    28] INT32       0

2024.07.11 18:04:10.470 *D* [client.session.0   ] Message dump:
  ** 000000 | 00 91 00 40 00 00 00 78 00 00 00 0A 00 00 00 09 | ...@...x........
  ** 000010 | 00 00 00 A8 78 DA 2B 60 60 60 60 67 00 03 96 E2 | ....x.+````g....
  ** 000020 | CC AA 54 20 3D 11 CA 17 2A 49 2D 2E F1 CC 2B 28 | ..T =...*I-...+(
  ** 000030 | 2D 71 CF C9 4F 4A CC 09 4B 2C 62 60 28 60 60 60 | -q..OJ..K,b`(```
  ** 000040 | 84 A9 37 34 30 32 01 72 1F 31 03 09 A0 38 13 54 | ..7402.r.1...8.T
  ** 000050 | 9C AD 34 AF B4 38 35 85 01 06 98 21 94 BA 1A 88 | ..4..85....!....
  ** 000060 | 04 AA 63 66 67 40 06 8C BF 81 0A 98 80 8C 58 64 | ..cfg@........Xd
  ** 000070 | 51 00 AC 7B 11 90 00 00                         | Q..{....
  ** code=0x0091 (CMD_EXECUTE_SERVER_COMMAND) version=0 flags=0x0040 id=10 size=120 numFields=9
  ** 000000: [1879048192] UTF8-STRING "size"
  ** 000010: [   145] UTF8-STRING "testInputGlobalVar"
  ** 000030: [1879048193] UTF8-STRING "1024"
  ** 000040: [   482] INT16       1
  ** 000048: [1879048194] UTF8-STRING "unused"
  ** 000060: [     3] INT32       10022
  ** 000070: [1879048195] UTF8-STRING ""
  ** 000080: [   507] INT16       2
  ** 000088: [    93] INT32       0

2024.07.11 18:04:10.470 *D* [client.session.0   ] Received message CMD_EXECUTE_SERVER_COMMAND
2024.07.11 18:04:10.470 *D* [client.session.0   ] Sending message CMD_REQUEST_COMPLETED (32 bytes)
2024.07.11 18:04:10.470 *D* [client.session.0   ] Message dump:
  ** 000000 | 00 1D 50 00 00 00 00 20 00 00 00 0A 00 00 00 01 | ..P.... ........
  ** 000010 | 00 00 00 1C 00 00 00 00 00 00 00 07 00 00 00 00 | ................
  ** code=0x001D (CMD_REQUEST_COMPLETED) version=5 flags=0x0000 id=10 size=32 numFields=1
  ** 000000: [    28] INT32       7

2024.07.11 18:04:10.476 *D* [client.session.0   ] readSocket: connection closed
2024.07.11 18:04:10.477 *D* [client.session     ] All locks for session 0 removed