tests/integration: CollectorTest: increase threshold
Because these assertion failures keep happening intermittently:

[main] INFO org.netxms.client.NXCSession - Succesfully logged in, userId=1
[Network Message Receiver] INFO org.netxms.client.NXCSession - Network receiver thread stopped
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.19 s <<< FAILURE! -- in org.netxms.tests.CollectorTest
[ERROR] org.netxms.tests.CollectorTest.testThreshold -- Time elapsed: 2.094 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
        at org.netxms.tests.CollectorTest.testThreshold(CollectorTest.java:161)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

[DEBUG] Closing the fork 1 after saying GoodBye.
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   CollectorTest.testThreshold:161 expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0